apiVersion: v1
kind: Service
metadata:
  name: sensor-service
  labels:
    app: sensor-app   
spec:
  type: NodePort
  selector:
    app: sensor-app
  ports:
    - name: http      
      port: 80
      targetPort: 8000
      nodePort: 30007